### ISSUE TITLE
[AEM Forms] Cors issue when calling Servlet from React App

### ISSUE THREAD

**Issue by vidhyabhushanbahl** [AdobeDocs/experience-manager-learn.en#153]
Issue in ./help/forms/react-ic-sign/deploy-assets-on-your-server.md

Even after setting CORS as described getting following error.

"Access to fetch at 'http://localhost:4502/bin/getwidgeturl' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

**Comment by gbedekar** [comment]
You are trying to submit to the author instance which needs authentication. It is recommended to POST to an publish instance

**Comment by davidjgonzalez** [comment]
You can adapt the guidance for AEM Headless GQL CORS access [1]  to your use case - the path will be different, and the method as well. You also dont to have worry about caching since your URL doesnt have an extension.

[1] https://experienceleague.adobe.com/docs/experience-manager-learn/getting-started-with-aem-headless/deployments/configurations/cors.html?lang=en

**Comment by gbedekar** [comment]
Please see the above response.
