### ISSUE TITLE
Apache Joshua language packs are not available in the given link..

### ISSUE THREAD

**Issue by mharikrishna-adobe** [AdobeDocs/experience-manager-learn.en#196]
Issue in ./help/assets/translation/smart-translation-search-technical-video-setup.md
 
I tired downloading the Language packs given in https://cwiki.apache.org/confluence/display/JOSHUA/Language+Packs, but they are not available any more.

**Comment by davidjgonzalez** [comment]
Hi - Unfortunately it looks lije this project is dead (in Apache Attic) and unfortunately the lang packs were on Dropbox, which Apache doesn't back up. It doesn't appear there were mirrors anyhow (Adobe, or otherwise)... so from my conversations w/ Aapache team - they're simply gone. 

Due to this, i've removed the video content around this feature as it cannot be used without these.
