### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-learn.en#201]
Issue in ./help/assets/authoring/renditions.md
Link to [Create Renditions in AEM Assets](https://experienceleague.adobe.com/playlists/experience-manager-assets-create-renditions.html?lang=en) is broken.

**Comment by davidjgonzalez** [comment]
Hi @alisonasanchez - I dont see where there's a link to this playlist on the page you mention:

![2024-11-20 at 9 23 AM](https://github.com/user-attachments/assets/c4e6ee6f-47c4-414f-9498-a97164d04d81)

The link youre saying is on the page (which i cant seem to see) is:

* hhttps://experienceleague.adobe.com/playlists/experience-manager-assets-create-renditions.html?lang=en

While the actual URL for this page is:

* https://experienceleague.adobe.com/en/playlists/experience-manager-assets-create-renditions

So the link youre seeing is missing the `/en/` path segment and using the a `.html` extension.

Not sure what to do though, since I dont see this link anywhere on the page to correct. Can you provide a screenshot of where this link appears on the page?

**Comment by alisonasanchez** [comment]
The page looks different than it did a couple of days ago. The bottom of the page had links, one of which was broken. In any case, it would be nice to have links to the documentation which goes into detail about the content in the tutorial.
