### ISSUE TITLE
Relative URLs in a sitemap.xml file? Shouldn't they be absolute?

### ISSUE THREAD

**Issue by jonburkedesign** [AdobeDocs/experience-manager-learn.en#46]
Issue in ./help/sites/seo/sitemaps.md

In the video you show a sitemap being created with relative paths. I am 99.9% sure this is wrong... URLs in a sitemap.xml files should be absolute.

Both Google and sitemaps.org show examples using absolute paths. Also, if you go to any reputable website with a sitemap.xml file, they all include absolute URLs... I also, submitted a sitemap to Google Search Console that included relative paths (as the video says is ok). Every URL came back as invalid.

If you have any reputable sources stating relative URLs are valid, please share them with me (I wasn't able to find any)... Otherwise, please update your documentation.

**Comment by bcmoney** [comment]
To back @jonburkedesign up, Adobe's own website shows absolute URLs as well:
- Sitemap index: https://www.adobe.com/hub/sitemap.xml
- actual language-specific Sitemap example: https://www.adobe.com/hub/sitemap-en.xml
Any particular reason that it won't automatically inherit the Base URL for a given content tree? Can this be made a configurable option maybe at the very least?

**Comment by davidjgonzalez** [comment]
@jonburkedesign / @bcmoney - Is this a feature request for AEM's sitemaps? Or are you saying that now the AEM Sitemaps use absolutely URLs, and the video content is misleading?

The video was recorded using the OOTB functionality, so the content is what it is. If you see that the feature itself has been updated to use absolute URLs, we can put a note beneath the video stating that absolute URLs are used now.

This Git repo is for the content (not feature enhancement) which is why I seem confused :)

**Comment by davidjgonzalez** [comment]
Adding info to describe how to set absolute URLs using Sling Mapping
