### ISSUE TITLE
[AEM Assets] Missing AEM as Cloud Service documentation on IDS setup

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-learn.en#74]
Issue in ./help/assets/asset-templates/asset-templates-technical-video-setup.md

Is there a documentation for asset templates that is compliant with AEM as Cloud Service? If not it would be great to create one - as far as I understand the current one will not help to set this up in the cloud approach

**Comment by davidjgonzalez** [comment]
@bartoszWesolowski I believe the steps for setting IDS up with the AEM SDK are the same.

The AEM as a Cloud Service environment setup is handled in conjunction with Adobe, since the IDS server when integrating with AEM CS is hosted by Adobe as well (so not sure you would have the details to configure).

If i can find formal docs ill post back here and update the linked page.

**Comment by davidjgonzalez** [comment]
Since IDS must be hosted in AMS when using it with AEM as a Cloud Service you need to work with your AEM account team to get this integration setup.

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/release-notes/release-notes/2020/release-notes-2020-12-0.html?lang=en
