### ISSUE TITLE
Error inserting breadcrumb component

### ISSUE THREAD

**Issue by marlonnelson** [AdobeDocs/experience-manager-learn.en#77]
Issue in help/getting-started-wknd-tutorial-develop/pages-templates.md

I'm hoping I can get some help here, some insight into the problem, or at least get pointed to the right spot to get help.  Thanks.

When following along in the tutorial, I get the following error when trying to add a breadcrumb to the Article Page Template:

![screencapture-localhost-4502-editor-html-conf-wknd-settings-wcm-templates-article-page-template-structure-html-2020-08-26-12_44_38](https://user-images.githubusercontent.com/2924369/91332399-1f0ac200-e79a-11ea-8bac-c12a04dcd2d0.png)

**Comment by godanny86** [comment]
hi @marlonnelson I don't think this is anything on your end. 
I think you are running into: https://github.com/adobe/aem-core-wcm-components/issues/1146. 

This issue should be fixed in the next release of Core Components. What version of Core Components are you on? I'm not sure when the bug got introduced. For the sake of the tutorial you could skip that step...

**Comment by marlonnelson** [comment]
I'm using core components 2.11.0 with AEM 6.4.8.0.

I've proceeded and somehow the breadcrumb component ended up in my template.

I'll wait for the bug fixes.

Thanks.
